### PR TITLE
ES6 sink support for SMT's

### PR DESCRIPTION
**Pull request by kujon**
Hi there 👋 

we're upgrading to ES6, so here's the version 6 equivalent of the one I've done in the past (https://github.com/lensesio/kafka-helm-charts/pull/105).

Hope you find it useful.

### CODE REVIEW

**Comment by maksyms** [comment]
@kujon Do you want to bring the branch up-to-date with the base before the review?

**Comment by kujon** [comment]
Hi Guys,

do you know when this will likely get reviewed/merged?

**Comment by spirosoik** [comment]
@kujon @maksyms thanks for the contribution guys

**Comment by kujon** [comment]
You're welcome!

**Pull request merged**
